#gateway-server:
#  image: gateway-server
#  container_name: gateway-server
#  dns: 172.17.0.1
#  ports:
#    - "9000:9000"
#  environment:
#    EUREKA_SERV: http://eureka:8761/eureka/
#    RABBITMQ_HOST: rabbitmq
#  links:
#    - rent-service
#    - payment-service
#    - turbine-server
#    - ops-server
#    - rabbitmq
#    - eureka-server
#  restart: always
#
#ops-server:
#  image: ops-server
#  container_name: ops-server
#  dns: 172.17.0.1
#  ports:
#    - "9411:9411"
#  restart: always
#
#turbine-server:
#  image: turbine-server
#  container_name: turbine-server
#  dns: 172.17.0.1
#  environment:
#    RABBITMQ_HOST: rabbitmq
#  links:
#    - rent-service
#    - payment-service
#    - rabbitmq
#  ports:
#    - "9001:9001"
#  restart: always
#
#consul:
#  image: gliderlabs/consul-server:0.5
#  container_name: consul
#  ports:
#    - "8400:8400"
#    - "8500:8500"
#    - "53:8600/udp"
#  command: "-bootstrap -advertise 192.168.99.100 -ui-dir /ui"
#  restart: always
#
##registrator:
##  image: gliderlabs/registrator
##  container_name: registrator
##  net: "host"
##  volumes:
##    - "/var/run/docker.sock:/tmp/docker.sock"
##  command: "-ip 192.168.99.100 consul://192.168.99.100:8500"
##  restart: always
#
second-microservice:
  image: second-microservice
  dns: 172.17.0.1
  ports:
    - "8080"
  links:
    - rabbitmq
    - eureka-server
    - first-microservice
  environment:
    RABBITMQ_HOST: rabbitmq
    EUREKA_SERV: http://eureka:8761/eureka/
    SERVICE_NAME: second-microservice
#    SERVICE_CHECK_HTTP: /health
    SPRING_PROFILES_ACTIVE: consul
#    SPRING_ZIPKIN_BASEURL: http://192.168.99.100:9000

first-microservice:
  image: first-microservice
  dns: 172.17.0.1
  ports:
    - "8080"
  links:
    - rabbitmq
    - eureka-server
  environment:
    RABBITMQ_HOST: rabbitmq
    EUREKA_SERV: http://eureka:8761/eureka/
    SERVICE_NAME: first-microservice
#    SERVICE_CHECK_HTTP: /health
    SPRING_PROFILES_ACTIVE: consul
#    SPRING_ZIPKIN_BASEURL: http://192.168.99.100:9000

rabbitmq:
  image: rabbitmq:3-management
  hostname: rabbitmq
  ports:
    - "5672:5672"
    - "15672:15672"

eureka-server:
  image: eureka-server
  dns: 172.17.0.1
  hostname: eureka
  ports:
    - "8761:8761"
  environment:
    RABBITMQ_HOST: rabbitmq
    SERVICE_NAME: eureka-service
#    SERVICE_CHECK_HTTP: /health
#    SPRING_ZIPKIN_BASEURL: http://192.168.99.101:9000