#!/bin/bash

docker-compose up -d rabbitmq
docker-compose up -d zipkin
./rebuild-eureka-server
./rebuild-first-microservice
./rebuild-second-microservice
./rebuild-turbine-server
./rebuild-gateway-server
